baseURL = 'https://adtygan.github.io/'
languageCode = 'en-us'
title = 'Aditya Ganesh Kumar'
paginate = 5
paginatePath = 'posts'
theme = "PaperMod"
enableEmoji = true

[params]
author = "Aditya Ganesh Kumar"
title = "Aditya Ganesh Kumar"
description = "Aditya's homepage and personal blog"

defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false


[params.homeInfoParams]
  Title = "Greetings 👋🏻"
  Content = """
- I'm Aditya, an AI practitioner and tinkerer. I recently graduated 
  from the National University of Singapore where I was advised by 
  [Prof. Lee Wee Sun](https://www.comp.nus.edu.sg/~leews/), and worked
 on improving text-to-image retrieval systems for product matching.

 - I'm deeply passionate about **Human Centered AI** and believe in an exciting future
 where AI increasingly augments human creativity. I'll be using this space to document
 the interesting projects I cook up.
"""

[[params.socialIcons]]
name = "Github"
url = "https://github.com/adtygan"
weight = 1


[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/adtygan"
weoight = 2

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/adityaganeshkumar/"
weight = 3

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
weight = 4

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "cv"
name = "CV"
url = "https://drive.google.com/file/d/1FeJgCIoOV-KO3stURiFWa9K8RVYpLed3/view?usp=sharing"
weight = 20

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "gruvbox"

